"""Initial schema migration

Revision ID: 284b00ce8df9
Revises: 
Create Date: 2026-07-04 16:29:16.500947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284b00ce8df9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
