"""Add rent electricity and messages

Revision ID: 5fc4859dfc53
Revises: b3c2e7f9a012
Create Date: 2026-07-05 21:20:57.568333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc4859dfc53'
down_revision = 'b3c2e7f9a012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('electricity_bill', sa.Float(), nullable=True))

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'hostels', ['hostel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'hostels', ['hostel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('electricity_bill')
        batch_op.drop_column('rent')

    op.drop_table('messages')
    # ### end Alembic commands ###
